name: Visitor Counter

on:
  repository_dispatch:
    types: [increment]

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Increment counter
      run: |
        count=$(jq '.visits + 1' counter.json)
        echo "{\"visits\": $count}" > counter.json

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add counter.json
        git commit -m "Increment visit" || echo "No changes to commit"
        git push
